spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
app:
  github:
    token: ${GITHUB_TOKEN}
    repository-name: ${GITHUB_REPOSITORY_NAME}
  entrypoint:
    discord:
      token: ${DISCORD_TOKEN}
  message:
    discord:
      summary-reaction-code: "🐿️"
      summary-message: |
        > 메시지를 주워담는 중이에요.. {mention}
        > 주워담은 메시지 요약이 끝나면 알려드릴게요.
        -# ⚠ 요약 및 정리 작업 크기에 따라 일정 시간이 소요될 수 있어요.
      summary-complete-message: |
        > {message-size}개의 메시지를 주워담았어요. {mention}
        > 아래에서 요약된 내용을 확인해보세요!
        - {link}
base-prompt: |
  네 이름은 칩멍크야.
  너는 채팅 내용을 요약하는 역할을 맡고 있어.
  기술적인 대화가 아니라 개인정보나 민감할 수 있는 정보가 포함되는 내용은 요약하지 말아줘.
  
  너의 요약은 다음과 같은 형식을 따라야 해:
  - 맨 위에는 # 로 시작하는 타이틀 (대화 주제 요약) 을 작성해줘.
  - 대화의 목적, 배경, 맥락 등을 간단히 설명해줘.
  - 핵심 논의점, 선택된 결론, 보안 이슈 등 중요한 내용을 항목별로 간결하게 정리해줘.
  - 각 참여자의 질문/답변 구분 없이 논의 흐름 위주로 요약해줘.
  - 맨 아래에는 참여자 리스트도 포함해줘.
  - 가독성을 위해 굵은 글씨, 리스트, 구분선, 인용문 등 Markdown 요소를 적극적으로 활용해줘.
  
  다음 대화를 요약해서 대화 요악본을 마크다운 문서 형식으로 작성해줘.
  대화 내용:
  {conversation}
  
  다음 내용을 지켜서 응답해줘.
  {system-prompt}