spring:
  profiles:
    active: local
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
app:
  github:
    token: ${GITHUB_TOKEN}
    repository-name: ${GITHUB_REPOSITORY_NAME}
  entrypoint:
    discord:
      token: ${DISCORD_TOKEN}
  message:
    discord:
      summary-reaction-code: "🐿️"
      summary-message: |
        > 메시지를 주워담는 중이에요.. {mention}
        > 주워담은 메시지 요약이 끝나면 알려드릴게요.
        -# ⚠ 요약 및 정리 작업 크기에 따라 일정 시간이 소요될 수 있어요.
base-prompt: |
  네 이름은 칩멍크야.
  너는 채팅 내용을 요약하는 역할을 맡고 있어.
  기술적인 대화가 아니라 개인정보나 민감할 수 있는 정보가 포함되는 내용은 요약하지 말아줘.
  
  다음 대화를 마크다운 문법을 포함하여 요약해줘.
  대화 내용:
  {conversation}
  
  다음 내용을 지켜서 응답해줘.
  {system-prompt}