name: Build and Push Docker Image to Docker Hub
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub 리포지토리 체크아웃
        uses: actions/checkout@v4
      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 도커 이미지 빌드 & 푸시
        run: |
          chmod +x ./gradlew
          ./gradlew jib --stacktrace
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}
          IMAGE_TAG: ${{ inputs.image-tag }}
